stages:
  stage_00_data_ingestion:
    cmd: python3 IMDB/app_src/stage_00_data_ingestion.py
    deps:
    - IMDB/app_src/stage_00_data_ingestion.py
    - IMDB/app_config/configuration.py
    - config/config.yaml
    outs:
    - IMDB/app_artifact/stage00_data_ingestion/ingested_data/Test.csv
    - IMDB/app_artifact/stage00_data_ingestion/ingested_data/Train.csv

  stage_01_data_transformation:
    cmd : python3 IMDB/app_src/stage_01_data_transformation.py
    deps:
    - IMDB/app_src/stage_01_data_transformation.py
    - IMDB/app_config/configuration.py
    - config/config.yaml
    outs:
    - IMDB/app_artifact/stage01_data_transformation/preprocessed/preprocessed.pkl
    - IMDB/app_artifact/stage01_data_transformation/transformed_data/test/test.npz
    - IMDB/app_artifact/stage01_data_transformation/transformed_data/train/train.npz

  stage_02_model_trainer:
    cmd: python3 IMDB/app_src/stage_02_model_trainer.py
    deps:
    - IMDB/app_src/stage_02_model_trainer.py
    - IMDB/app_config/configuration.py
    - config/config.yaml
    - IMDB/app_entity/model_factory.py
    - config/model.yaml
    outs:
    - IMDB/app_artifact/stage02_model_training/trained_model/model.pkl
  
  stage_03_model_evaluation:
    cmd: python3 IMDB/app_src/stage_03_model_evaluation.py
    deps:
    - IMDB/app_src/stage_03_model_evaluation.py
    - IMDB/app_config/configuration.py
    - config/config.yaml
    - IMDB/app_artifact/stage02_model_training/trained_model/model.pkl
    outs:
    - IMDB/app_artifact/stage03_model_evaluation/