grid_search:
  module: sklearn.model_selection
  class: GridSearchCV
  params:
    cv: 2
    verbose: 3
    n_jobs : -1


model_selection:
  model_1:
    module: sklearn.ensemble
    class: RandomForestClassifier
    search_param_grid:
        n_estimators: [100, 200]
        max_depth: [ 7, 8, 9, 10]
