grid_search:
  module: sklearn.model_selection
  class: GridSearchCV
  params:
    cv: 2
    verbose: 2
    n_jobs : -1


model_selection:
  model_1:
    module: sklearn.ensemble
    class: RandomForestClassifier
    search_param_grid:
      criterion:
        - 'gini'
        - 'entropy'
      n_estimators :
        - 100
  model_2:
    module: sklearn.linear_model
    class: LogisticRegression
    search_param_grid:
      penalty:
        - 'l1'
        - 'l2'